#!/usr/bin/env node
import 'dotenv/config';
import { Command } from 'commander';
import { SolverConfig } from '../config/SolverConfig';
import { SolverRunner } from './SolverRunner';

const program = new Command();

program
  .name('velox-solver')
  .description('Velox Solver SDK - Run a solver instance on Movement')
  .version('1.0.0');

program
  .command('start')
  .description('Start the solver instance')
  .option('-c, --config <path>', 'Path to .env config file')
  .option('--dry-run', 'Run in dry-run mode (no transactions)')
  .option('--skip-registration-check', 'Skip solver registration verification')
  .option('-v, --verbose', 'Enable verbose logging')
  .action(async (options) => {
    try {
      // Load config from specified file or default .env
      if (options.config) {
        require('dotenv').config({ path: options.config });
      }

      // Override with CLI flags
      if (options.dryRun) {
        process.env.DRY_RUN = 'true';
      }
      if (options.verbose) {
        process.env.LOG_LEVEL = 'debug';
      }

      const config = SolverConfig.fromEnv();
      const errors = config.validate();

      if (errors.length > 0) {
        console.error('\n❌ Configuration errors:');
        errors.forEach((e) => console.error(`   - ${e}`));
        process.exit(1);
      }

      const runner = new SolverRunner(config);
      await runner.start(!options.skipRegistrationCheck);
    } catch (error) {
      console.error('\n❌ Failed to start solver:', (error as Error).message);
      process.exit(1);
    }
  });

program
  .command('status')
  .description('Check solver registration status and stats')
  .action(async () => {
    try {
      const config = SolverConfig.fromEnv();
      const runner = new SolverRunner(config);
      await runner.showStatus();
    } catch (error) {
      console.error('\n❌ Failed to get status:', (error as Error).message);
      process.exit(1);
    }
  });

program
  .command('check-config')
  .description('Validate configuration without starting')
  .action(() => {
    try {
      const config = SolverConfig.fromEnv();
      const errors = config.validate();

      if (errors.length > 0) {
        console.error('\n❌ Configuration errors:');
        errors.forEach((e) => console.error(`   - ${e}`));
        process.exit(1);
      }

      console.log('\n✅ Configuration is valid!\n');
      console.log(config.toSummary());
    } catch (error) {
      console.error('\n❌ Configuration error:', (error as Error).message);
      process.exit(1);
    }
  });

program
  .command('init')
  .description('Generate a sample .env configuration file')
  .option('-o, --output <path>', 'Output path', '.env')
  .action((options) => {
    const fs = require('fs');
    const path = require('path');

    const envContent = `# ================================================
# Velox Solver Configuration
# ================================================
# Generated by @velox/solver-sdk

# === REQUIRED ===================================

# Movement Network RPC endpoint
RPC_URL=https://testnet.movementnetwork.xyz/v1

# Velox contract address
VELOX_ADDRESS=0x951cb360d9b1d4cb4834cf76e4fca0f63a85237874d8b2d45b3056439b91cbb7

# Your registered solver wallet private key (hex format, with or without 0x prefix)
# IMPORTANT: Register this wallet as a solver on the Velox UI first!
SOLVER_PRIVATE_KEY=

# === OPTIONAL - Network =========================

# GraphQL endpoint for faster queries (optional)
# GRAPHQL_URL=

# Shinami Node Service API key for enhanced reliability (optional)
# SHINAMI_KEY=

# === OPTIONAL - Solver Behavior =================

# Polling interval for new intents (milliseconds)
POLLING_INTERVAL=5000

# Skip existing intents when solver starts
SKIP_EXISTING=true

# Maximum concurrent intent processing
MAX_CONCURRENT=5

# Enable dry-run mode (simulate without submitting transactions)
DRY_RUN=false

# === OPTIONAL - Intent Types ====================
# Set to 'false' to disable specific intent types

ENABLE_SWAP=true
ENABLE_LIMIT_ORDER=true
ENABLE_TWAP=true
ENABLE_DCA=true
ENABLE_SEALED_BID_AUCTION=true
ENABLE_DUTCH_AUCTION=true

# === OPTIONAL - Intent Filtering ================

# Minimum/maximum input amount to consider (in smallest units)
# MIN_INPUT_AMOUNT=0
# MAX_INPUT_AMOUNT=18446744073709551615

# Whitelist specific tokens (comma-separated addresses, empty = all allowed)
# INPUT_TOKEN_WHITELIST=0x1::aptos_coin::AptosCoin,0x...
# OUTPUT_TOKEN_WHITELIST=0x1::aptos_coin::AptosCoin,0x...

# === OPTIONAL - Profitability ===================

# Minimum profit margin in basis points (100 = 1%)
MIN_PROFIT_BPS=10

# Spread to apply for solver margin in basis points
SPREAD_BPS=10

# Maximum gas price willing to pay (in octas)
MAX_GAS_PRICE=1000

# Skip intents with less than X seconds to deadline
MIN_DEADLINE_SECONDS=30

# === OPTIONAL - Limit Orders ====================

# How often to check limit order prices (milliseconds)
LIMIT_ORDER_CHECK_INTERVAL=15000

# Enable partial fills for limit orders
ENABLE_PARTIAL_FILLS=true

# === OPTIONAL - DCA/TWAP ========================

# Continue monitoring scheduled intents
MONITOR_SCHEDULED=true

# How often to check scheduled intent readiness (milliseconds)
SCHEDULED_CHECK_INTERVAL=5000

# === OPTIONAL - Auctions ========================

# Dutch auction strategy: conservative | moderate | aggressive
# - conservative: Wait for price to drop significantly
# - moderate: Accept at market price or slightly above
# - aggressive: Accept early at higher prices
DUTCH_AUCTION_STRATEGY=moderate

# Max price willing to accept in Dutch auctions (percentage of market price)
DUTCH_MAX_PRICE_PERCENT=102

# Sealed bid auction strategy: conservative | moderate | aggressive
SEALED_BID_STRATEGY=moderate

# === OPTIONAL - Logging & Monitoring ============

# Log level: debug | info | warn | error
LOG_LEVEL=info

# Enable colored console output
COLORED_OUTPUT=true

# Webhook URL for notifications (Discord, Slack, etc.)
# WEBHOOK_URL=https://hooks.slack.com/...

# Enable Prometheus metrics endpoint
ENABLE_METRICS=false

# Metrics endpoint port
METRICS_PORT=9090
`;

    const outputPath = path.resolve(options.output);

    if (fs.existsSync(outputPath)) {
      console.error(`\n❌ File already exists: ${outputPath}`);
      console.log('   Use a different path with -o flag or remove existing file');
      process.exit(1);
    }

    fs.writeFileSync(outputPath, envContent);
    console.log(`\n✅ Created configuration file: ${outputPath}`);
    console.log('\n📝 Next steps:');
    console.log('   1. Edit the .env file and set your SOLVER_PRIVATE_KEY');
    console.log('   2. Register your wallet as a solver on Velox UI');
    console.log('   3. Run: npx velox-solver start');
  });

program.parse();
